name: Feature request
description: Suggest an idea for this project
title: ''
labels: ''
assignees: ''

body:
  - type: textarea
    id: problem_description
    attributes:
      label: Problem Description
      description: Is your feature request related to a problem? Please describe it.
      placeholder: A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

  - type: textarea
    id: solution_description
    attributes:
      label: Desired Solution
      description: Describe the solution you'd like.
      placeholder: A clear and concise description of what you want to happen.

  - type: textarea
    id: alternatives_description
    attributes:
      label: Alternative Solutions
      description: Describe any alternative solutions or features you've considered.
      placeholder: A clear and concise description of any alternative solutions or features you've considered.

  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context
      description: Add any other context or screenshots about the feature request here.
      placeholder: Provide any additional context...
