name: markdown-lint
on:
    pull_request:
      paths:
      - mkdocs/**
jobs:
  markdown_lint:
    runs-on: ubuntu-latest
    steps:
        - uses: DavidAnson/markdownlint-cli2-action@v18
          with:
            globs: '**/*.md'
